### ISSUE TITLE
Traefik bouncer helm chart installation error (k8s 1.30.3, traefik v3)

### ISSUE THREAD

**Issue by urbaman** [crowdsecurity/helm-charts#176]
Hi,

Trying to install the traefik bouncer has throws the following error:

```
helm upgrade -i -n traefik traefik-bouncer crowdsec/crowdsec-traefik-bouncer -f crowdsec-traefik-bouncer-values.yaml
Release "traefik-bouncer" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "traefik-bouncer" namespace: "" from "": no matches for kind "Middleware" in version "traefik.containo.us/v1alpha1"
ensure CRDs are installed first
```

Is there a problem with the old "traefik.containo.us/v1alpha1" traefik CRDs?

Thanks.

**Comment by urbaman** [comment]
As a note: cloning the repo and installing the chart from local fixed the problem, so probably the helm install from remote has problems?

**Comment by hertznsk** [comment]
> As a note: cloning the repo and installing the chart from local fixed the problem, so probably the helm install from remote has problems?

The problem is that the traefik-bouncer version has not been released, which has change #169.

Please, someone do it.

**Comment by LaurenceJJones** [comment]
> > As a note: cloning the repo and installing the chart from local fixed the problem, so probably the helm install from remote has problems?
> 
> The problem is that the traefik-bouncer version has not been released, which has change #169.
> 
> Please, someone do it.
> 
> /kind bug

The reason is because we dont support this chart anymore since the image hasnt been updated in 2 years. Seems [this pr](https://github.com/crowdsecurity/helm-charts/commit/a1eb8d07822a220254b2fd98e9b99695e99a2480) removed the warning at the top of the readme.

**Comment by hertznsk** [comment]
> The reason is because we dont support this chart anymore since the image hasnt been updated in 2 years (its a third party image). Seems [this pr](https://github.com/crowdsecurity/helm-charts/commit/a1eb8d07822a220254b2fd98e9b99695e99a2480) removed the warning at the top of the readme.

Thank you for your valuable comment!

It seems that I may have set up the process incorrectly. I followed this article <https://docs.crowdsec.net/u/getting_started/installation/kubernetes/> to guide me through the process, but at the stage of creating the middleware, I thought it would be easier to use a helm chart instead of doing it manually.

However, your link to the plugin was more helpful in terms of correctly setting up the process.

Perhaps we could add some instructions on how to install the plugin to the documentation and remove the old helm chart code from the main page. This would help other users who might be facing similar issues. Thank you again for your input!

**Comment by LaurenceJJones** [comment]
Classing this issue as _kind of_ resolved, we need to work on documentation for it which we have an internal task to write up a whole k8s guide hosted on https://docs.crowdsec.net/ instead of relying on the automatically generate helm readme's.

If you have anymore issues please reopen an issue, if the issue is linked to the now deprecated chart then please upgrade to the newer plugin model.
